#url_shortener_base_url: "https://prv.ec"
public_base_url: http://0.0.0.0:50028

urls_db_path: urls.db

web_server_port: 50028

frontend_doc_root:

# ReCAPTCHA v2 API key
captcha_service_api_key:

# number of characters in the slug that identifies a shortened URL
# a slug is the "3fj83f" in "https://prv.ec/3fj83f"
slug_length: 7

# universe of characters to use to generate slugs
alphabet: 123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz

static_file_doc_root: /dev/null
web_server_bind_host: 0.0.0.0
trusted_certificates_path: /etc/ssl/certs/ca-certificates.crt

# maximum number of non-GET requests per IP per minute
rate_limit_per_minute: 5
# Seconds between garbage collecting list of IPs for rate-limiting purposes
rate_limiter_ttl_seconds: 86400

# This 256-bit key uniquely generates URL slugs from URLs.
# Change this if you want to make sure your site generates slugs different from what prv.ec produces.
# (You probably don't need to change this.)
# Generate this with `openssl rand -hex 32`
url_generator_salt: db14ced8a70c850d08c2932b16cc12d90f3384f3a0eac960de63befc506b8057

# IP ranges known to belong to your reverse proxy that sits before this application
known_reverse_proxy_ip_ranges: []

# IP ranges known to belong to Cloudflare.
# See: https://www.cloudflare.com/ips/
# You probably do not need to change these.
known_cloudflare_ip_ranges: [
  2400:cb00::/32,
  2606:4700::/32,
  2803:f800::/32,
  2405:b500::/32,
  2405:8100::/32,
  2a06:98c0::/29,
  2c0f:f248::/32,
  173.245.48.0/20,
  103.21.244.0/22,
  103.22.200.0/22,
  103.31.4.0/22,
  141.101.64.0/18,
  108.162.192.0/18,
  190.93.240.0/20,
  188.114.96.0/20,
  197.234.240.0/22,
  198.41.128.0/17,
  162.158.0.0/15,
  104.16.0.0/13,
  104.24.0.0/14,
  172.64.0.0/13,
  131.0.72.0/22
]
